[package]
name = "random-id-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.11"
uuid = { version = "1.10", features = ["v4", "fast-rng"] }
nanoid = "0.4"
rand = "0.8"
arboard = "3.4"
console = "0.15"
